"""empty message

Revision ID: 5f17ad60c336
Revises: a02721e6f301
Create Date: 2021-11-10 23:23:15.160082

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5f17ad60c336'
down_revision = 'a02721e6f301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    op.drop_index('density', table_name='planet')
    op.drop_index('density_2', table_name='planet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('density_2', 'planet', ['density'], unique=False)
    op.create_index('density', 'planet', ['density'], unique=False)
    op.alter_column('planet', 'gravity',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    # ### end Alembic commands ###
